### PR TITLE
extinfo: Bring back alias information

### PR DESCRIPTION
**Pull request by bonki**
This fixes MON-6841

### CODE REVIEW

**Comment by tvestelind** [comment]
@tsjondin could you review this? :)

**Comment by bonki** [comment]
Ping?

**Comment by tsjondin** [comment]
Hi Bonki,

The alias is displayed on the extinfo page in the toolbar, which states:

Host <host_name> (<host_alias>)

If this is not enough the alias could be moved but should then be removed from the toolbar as well!

**Comment by jacobbaungard** [comment]
Stale, closing.

**Pull request closed without merging**
