### PR TITLE
Remove logger related permission levels

### PR DESCRIPTION
**Pull request by akselsjogren**
Remove permission levels previously used for Logger, since it's not part
of Monitor as of version 9.

Part of MON-12624.

Signed-off-by: Aksel Sjögren <asjogren@itrsgroup.com>

### CODE REVIEW

**Comment by jimorie** [comment]
I see that we have previously managed these access levels in `install_scripts/migrate_auth.php`, but then migrating *into* them. Do you know if this is something we need to consider now?

**Comment by akselsjogren** [comment]
> I see that we have previously managed these access levels in `install_scripts/migrate_auth.php`, but then migrating _into_ them. Do you know if this is something we need to consider now?

We considered implementing removal of deprecated permissions in `migrate_auth.php` - but it could be problems if a user did something like `yum update; yum history undo ...`. So we decided that it's best to not remove anything from a `auth_groups.yml` file that the user has modified. It shouldn't hurt that deprecated permissions are left, I think..

**Comment by jimorie** [comment]
> We considered implementing removal of deprecated permissions in `migrate_auth.php` - but it could be problems if a user did something like `yum update; yum history undo ...`. So we decided that it's best to not remove anything from a `auth_groups.yml` file that the user has modified. It shouldn't hurt that deprecated permissions are left, I think..

All right! That's good with me. :+1:

**Review by jimorie — APPROVED** [review]
:+1:

**Pull request merged**
